### ISSUE TITLE
vagrant up rundeck fails

### ISSUE THREAD

**Issue by mnpoonia** [rundeck/anvils-demo#18]
It throws error

==> rundeck: package epel-release is not installed
==> rundeck: warning: 
==> rundeck: epel-release.rpm: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
==> rundeck: Preparing...  
==> rundeck: ##################################################
==> rundeck: epel-release  
==> rundeck: ####
==> rundeck: ###
==> rundeck: ##
==> rundeck: #
==> rundeck: ########################################
==> rundeck: Loaded plugins: fastestmirror
==> rundeck: Setting up Install Process
==> rundeck: Determining fastest mirrors
==> rundeck: Error: Cannot find a valid baseurl for repo: base
==> rundeck: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=stock error was
==> rundeck: 14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by senk** [comment]
Working fine for me maybe some firewall or internet connection issues on your host?

**Comment by rmaddodi** [comment]
Hi,

I am getting error while running vagrant up. Any idea?

==> rundeck: http://download.fedoraproject.org/pub/epel/6/x86_64/repodata/50ffc99b50878f035e9a1ba03c24feb096bee363f560d519c0b94479298c13c3-primary.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
==> rundeck: Trying other mirror.
==> rundeck: http://download.fedoraproject.org/pub/epel/6/x86_64/repodata/50ffc99b50878f035e9a1ba03c24feb096bee363f560d519c0b94479298c13c3-primary.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
==> rundeck: Trying other mirror.
==> rundeck: Error: failure: repodata/50ffc99b50878f035e9a1ba03c24feb096bee363f560d519c0b94479298c13c3-primary.sqlite.bz2 from epel: [Errno 256] No more mirrors to try.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by PeterGarlic** [comment]
@rmaddodi Should be any kind of problem:
repository not responding, dns configuration, proxy configuration, internet connection......
what hardware and network connection do you have?

@mnpoonia are you using a proxy? 
If yes try this: https://github.com/tmatilai/vagrant-proxyconf

**Comment by ahonor** [comment]
Epel release is no longer required and was removed from the provisioning scripts.
