### ISSUE TITLE
Getting epel signature key error. Work around is included

### ISSUE THREAD

**Issue by wayneyuen99** [rundeck/anvils-demo#20]
When I run Vagrant up, I got the following error:
# 

==> rundeck: Running provisioner: shell...
    rundeck: Running: /var/folders/2b/sm629k7s5jsbvvytwdwgck5h0000gp/T/vagrant-shell20160401-742-1n8296q.sh
==> rundeck: package epel-release is not installed
==> rundeck: warning:
==> rundeck: epel-release.rpm: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
==> rundeck: Preparing...
==> rundeck: ##################################################
==> rundeck: epel-release
==> rundeck: ####
==> rundeck: ###
==> rundeck: ##
==> rundeck: #
==> rundeck: ########################################
==> rundeck: Loaded plugins: fastestmirror
==> rundeck: Setting up Install Process
==> rundeck: Determining fastest mirrors
==> rundeck:  \* base: mirror.net.cen.ct.gov
==> rundeck:  \* extras: mirror.team-cymru.org
==> rundeck:  \* updates: mirror.cs.vt.edu
==> rundeck: http://download.fedoraproject.org/pub/epel/6/x86_64/repodata/566602a32471df51ece02fd5237d64df32389a839bb44ea47b4f8eff51cc1f67-primary.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
==> rundeck: Trying other mirror.
==> rundeck: http://download.fedoraproject.org/pub/epel/6/x86_64/repodata/566602a32471df51ece02fd5237d64df32389a839bb44ea47b4f8eff51cc1f67-primary.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
==> rundeck: Trying other mirror.
==> rundeck: Error: failure: repodata/566602a32471df51ece02fd5237d64df32389a839bb44ea47b4f8eff51cc1f67-primary.sqlite.bz2 from epel: [Errno 256] No more mirrors to try.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
# went wrong.

I am able to get around the problem by modifying the vagrant file to run "yum install epel-release" before running any bootstrap script.
# Following is my vagrant file

Vagrant.configure("2") do |config|
    PROJECT="anvils"
    RDIP="192.168.50.2"
    RUNDECK_YUM_REPO="https://bintray.com/rundeck/rundeck-rpm/rpm"
    #RUNDECK_YUM_REPO="https://bintray.com/rundeck/ci-staging-rpm/rpm"

```
config.vm.box = "bento/centos-6.7"

config.vm.define :rundeck do |rundeck|
    rundeck.vm.hostname = "rundeck.anvils.com"
    rundeck.vm.network :private_network, ip: "#{RDIP}"

            ### work around ######
    rundeck.vm.provision :shell, inline: "yum install epel-release -y"
            ####################

    rundeck.vm.provision :shell, :path => "install-rundeck.sh", :args => "#{RDIP} #{RUNDECK_YUM_REPO}"
    rundeck.vm.provision :shell, :path => "install-httpd.sh"
    rundeck.vm.provision :shell, :path => "install-rundeck-admin.sh", :args => "https://bintray.com/rerun/rerun-rpm/rpm http://#{RDIP}:4440"

    rundeck.vm.provision :shell, :path => "add-project.sh", :args => "#{PROJECT}"
end
```

end
#

**Comment by ahonor** [comment]
@wayneyuen99 thanks for this tip. I added it as a comment
