### ISSUE TITLE
ERROR in "main" /usr/lib/rerun/modules/rundeck-admin/commands/key-upload/script:78

### ISSUE THREAD

**Issue by PeterGarlic** [rundeck/anvils-demo#21]
Hi
I would start to say that I´ve read that you made this **strong example** running with vagrant 1.2.2 and centos 6.7 and i don´t know wich rundeck version.
But some time is gone, current vagrant is 1.8.4, centos has moved to 6.8 (and epel as well), rundeck is now at the version 2.6.8..... **and your project is still working**  with one exception. :(

All vagrant deployment works perfectly until the shell provisioner script call: This is the error log

==> rundeck: Running provisioner: shell...
rundeck: Running: /var/folders/vc/j_yqwz193jz5mmfnmpl7kcpc0000gp/T/vagrant-shell20160629-9534-13uutxy.sh
==> rundeck: id:
==> rundeck: www1: No such user
==> rundeck: Add host user www1.
==> rundeck: Generate SSH key for user www1
==> rundeck: ERROR in "main" /usr/lib/rerun/modules/rundeck-admin/commands/key-upload/script:78
==> rundeck: [error] rundeck-admin:key-upload: ERROR: login failure. http_code: 403
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

It seems that there is a small error inside the add-project.sh when calls the rundeck-admin, because users ans ssh keys are created correctly.

The funny thinks is that you run for four more times "vagrant provision" (that skip the rundeck-admin calls) at the end the vagrant deployment will end correctly. Ok, the rundeck VM have some problems, but it works!

If required the logs of the installation are available.
-Peter

**Comment by ahonor** [comment]
Refactored to use the new rundeck cli and removed use of previous rerun modules
