### ISSUE TITLE
Recommended CPU/Memory

### ISSUE THREAD

**Issue by rupert654** [rundeck/anvils-demo#23]
When bringing up the machine, I found Rundeck ran very slowly with requests taking a very long time.

I updated the Vagrantfile as follows:

    config.vm.provider "virtualbox" do |vb|
        vb.cpus = "2"
        vb.memory = "4096"
    end

It now runs very smoothly. Is it worth bumping the default memory/cpus? I'm not sure how much it needs or else I would open a pull request.

If it is not clear, it might be worth adding a commented out section with some suggested defaults, so those unfamiliar with Vagrant can quickly comment then out, and adjust as needed, if they experience performance issues.

**Comment by ahonor** [comment]
@rupert654 thanks for that tip. I'll add it as a comment.
