### ISSUE TITLE
Question: Vagrant version

### ISSUE THREAD

**Issue by PeterGarlic** [rundeck/anvils-demo#26]
Hi 
current Vagrant version is 1.9.1 while on documentation is specified version 1.2.2.
Will the "anvils-demo" works only with the 1.2.2 or is supported also on other version?
Thanks in advance
-Peter

**Comment by snifbr** [comment]
Hi Peter,

Anvils-demo works with current Vagrant version, but require some changes with rundeck provision scripts since rundeck 2.7.x.

I did some changes in my fork and works fine.

Regards,
Danilo

**Comment by PeterGarlic** [comment]
Hi Danilo
are these scripts available somehere?
-Peter

**Comment by ahonor** [comment]
@PeterGarlic I'm cleaning up the provisioning scripts. Also, in my test env it is now working for vagrant 1.8.6. I'll investigate 1.9.x.

**Comment by ahonor** [comment]
Now working with vagrant 1.9.1
