### ISSUE TITLE
Fails with error "No package rundeck available"

### ISSUE THREAD

**Issue by markvr** [rundeck/anvils-demo#9]
Hi,

When I try this, it fails with the error `No package rundeck available`.  Log output:
````
C:\temp\rundeck>git clone https://github.com/rundeck/anvils-demo.git
Cloning into 'anvils-demo'...
<snip>
C:\temp\rundeck>cd anvils-demo

C:\temp\rundeck\anvils-demo>vagrant up rundeck
Bringing machine 'rundeck' up with 'virtualbox' provider...
==> rundeck: Importing base box 'centos-63-x64'...
<snip>
==> rundeck: Setting up Install Process
==> rundeck: No package rundeck available.
==> rundeck: Error: Nothing to do

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
````

This is on Windows 7 x64 with VirtualBox 4.3.12 and Vagrant 1.7.2.  Is there any other info that would be useful?

**Comment by gschueler** [comment]
try uncommenting this line in Vagrantfile https://github.com/rundeck/anvils-demo/blob/master/Vagrantfile#L5

and remove the following line 6

this sets the repo to use the latest release version, not the CI staged version, which might not be present

**Comment by gschueler** [comment]
https://github.com/rundeck/anvils-demo/pull/13
